### ISSUE TITLE
Make sure pnc-e2e can login into the PNC instance

### ISSUE THREAD

**Issue by thescouser89** [emmettu/pnc-e2e#2]
[writing this issue so that @thescouser89 does not forget]

The credentials for the PNC instance shall not be committed to the repository. Instead it should be passed as a command line option, or as a properties file (an empty/dummy properties file can be committed to git). Let's also document in the README.md how to specify the credentials.

If no credentials are provided, then let's assume that the PNC instance does not require credentials.

**Comment by emmettu** [comment]
This has been implemented.

**Comment by thescouser89** [comment]
:+1:
