### ISSUE TITLE
No link to project newcastle

### ISSUE THREAD

**Issue by jiekang** [emmettu/pnc-e2e#5]
The README.md should contain a link to the project newcastle repository since this is related to it :)

**Comment by thescouser89** [comment]
WHY WAS THIS CLOSED

**Comment by jiekang** [comment]
To clear my issues list of open issues :)

**Comment by emmettu** [comment]
😡That is not the open source way Jie Kang

**Comment by thescouser89** [comment]
@emmettu  Stop commiting to private repos and open source everything!

**Comment by emmettu** [comment]
😢I turned in my open source badge and started working at a closed source company.
